export const tagToDisplayCategory = {
  レオパ: 'cage',
  フード: 'food',
  ヒーター: 'heater',
  温度管理: 'heater',
  湿度管理: 'humidifier',
  ケージ: 'cage',
  スターター: 'starter',
  初心者: 'starter',
  フトアゴ: 'lizard',
  カメレオン: 'lizard',
  消臭: 'care',
  栄養: 'food',
  ミルワーム: 'food',
  ゲル: 'food',
  ペレット: 'food',
}
